# states.py
#
from enum import Enum, auto
class State(Enum):
    DELAWARE = auto()
    CALIFORNIA = auto()
    # current capable states above
    ALABAMA = auto()
    ALASKA = auto()
    ARIZONA = auto()
    ARKANSAS = auto()
    COLORADO = auto()
    CONNECTICUT = auto()
    FLORIDA = auto()
    GEORGIA = auto()
    HAWAII = auto()
    IDAHO = auto()
    ILLINOIS = auto()
    INDIANA = auto()
    IOWA = auto()
    KANSAS = auto()
    KENTUCKY = auto()
    LOUISIANA = auto()
    MAINE = auto()
    MARYLAND = auto()
    MASSACHUSETTS = auto()
    MICHIGAN = auto()
    MINNESOTA = auto()
    MISSISSIPPI = auto()
    MISSOURI = auto()
    MONTANA = auto()
    NEBRASKA = auto()
    NEVADA = auto()
    NEW_HAMPSHIRE = auto()
    NEW_JERSEY = auto()
    NEW_MEXICO = auto()
    NEW_YORK = auto()
    NORTH_CAROLINA = auto()
    NORTH_DAKOTA = auto()
    OHIO = auto()
    OKLAHOMA = auto()
    OREGON = auto()
    PENNSYLVANIA = auto()
    RHODE_ISLAND = auto()
    SOUTH_CAROLINA = auto()
    SOUTH_DAKOTA = auto()
    TENNESSEE = auto()
    TEXAS = auto()
    UTAH = auto()
    VERMONT = auto()
    VIRGINIA = auto()
    WASHINGTON = auto()
    WEST_VIRGINIA = auto()
    WISCONSIN = auto()
    WYOMING = auto()
    DISTRICT_OF_COLUMBIA = auto()

    